### ISSUE TITLE
Able to select the OpenCL devices.

### ISSUE THREAD

**Issue by kice** [tanakamura/waifu2x-converter-cpp#10]
I have more than one GPU, and it always uses the first GPU but I would like to use my second GPU.

**Comment by tanakamura** [comment]
Hi kice,

I added `--list-processor` and `--processor` option to new waifu2x-converter-cpp.exe.
- http://int.main.jp/files/waifu2x-converter_x64_1018.zip
- http://int.main.jp/files/waifu2x-converter_x86_1018.zip

You can specify device by these options.

And, I added multiple device support to w2xcr.exe.
When you convert multiple files or directory from SendTo, it uses multiple devices automatically.
