### ISSUE TITLE
Alpha channel support?

### ISSUE THREAD

**Issue by wonderbeel** [tanakamura/waifu2x-converter-cpp#20]
Related issue
https://github.com/nagadomi/waifu2x/issues/27

**Comment by tanakamura** [comment]
I added this feature in this release.

http://int.main.jp/files/waifu2x-converter_x86_1130.zip
http://int.main.jp/files/waifu2x-converter_x64_1130.zip

Try it.

**Comment by wonderbeel** [comment]
Thanks, I can confirm that it works well in windows (haven't tested in linux but I presume that it works, will try in the next days).
