### ISSUE TITLE
Add a parameter to choose different GPU on system

### ISSUE THREAD

**Issue by HolyWu** [tanakamura/waifu2x-converter-cpp#8]
Hi  tanakamura,

Could you please add a parameter to let users be able to specify the device to use, if there are two graphics cards installed on the computer? Thank you very much.

Best regards,
HolyWu

**Comment by tanakamura** [comment]
HI HolyWu,

I added `--list-processor` and `--processor` option to waifu2x-converter-cpp.exe,
and added `w2xconv_get_processor_list`, `w2xconv_init_with_processor` API.

https://github.com/tanakamura/waifu2x-converter-cpp/blob/master/src/w2xconv.h#L145

Users can use specfic device by passing index of list that is obtained by `--list-processor`(or `w2xconv_get_processor_list`) to `--processor`(or `w2xconv_init_with_processor`).

Thanks,

**Comment by HolyWu** [comment]
Hi  tanakamura,

I will try it when I come off duty. Thanks for your hard effort!

Best regards,
HolyWu

**Comment by HolyWu** [comment]
Hi tanakamura,

When I execute `waifu2x-converter_x64.exe --list-processor`, I get:
   0: GeForce GTX 660                              (CUDA      ): num_core=5
   1: GeForce GTX 660                              (OpenCL    ): num_core=5
   2: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz    (FMA       ): num_core=8

But when I execute `waifu2x-converter_x86.exe --list-processor`, I get a different result:
   0: GeForce GTX 660                              (CUDA      ): num_core=5
   1: GeForce GTX 660                              (OpenCL    ): num_core=5
   2: Generic                                      (OpenCV    ): num_core=8

I am wondering why it can't detect the correct CPU name and type under 32 bits. Thanks.

Best regards,
HolyWu

**Comment by tanakamura** [comment]
HI WolyWu,
Thanks for your report.

Sorry, I missed build configuration.
Try new binary from http://int.main.jp/files/waifu2x-converter_x86_1018_02.zip
